### ISSUE TITLE
Cannot display AR content

### ISSUE THREAD

**Issue by helmiskandar** [jeromeetienne/AR.js#784]
**Describe the bug**
I'm developing AR project using Aframe + ar.js. the project was OK with few (I think less than 20 marker) marker..but then when I add more marker+AR content, it show error. Please refer below
 
**To Reproduce**
aframe-ar.js:19 Uncaught abort() at Error
at jsStackTrace (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:2:41099)
at stackTrace (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:2:41282)
at Object.abort (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:19:4866)
at _abort (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:2:106287)
at Uj (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:9:70106)
at Re (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:10:32411)
at ie (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:11:62784)
at je (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:11:64206)
at de (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:11:52972)
at wg (https://raw.githack.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js:10:85893)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Expected behavior**
it should be displayed AR content when the camera detect marker. but it display nothing and when I check the Inspect, it return error as above

**Screenshots**
![image](https://user-images.githubusercontent.com/57181650/100307056-d6081b00-2fdf-11eb-9bec-46c1f3bfdd16.png)

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [Version 87.0.4280.66 (Official Build) (64-bit)]

Hope someone can advice and suggest the solution. TQ

**Comment by kfarr** [comment]
So if I understand your issue correctly, your project was working as expected with 19 image markers but it no longer works with 20 or greater image markers in one active scene?

**Comment by helmiskandar** [comment]
yeah it is true..then it display error "out of memory".. I cannot figure it
out since there is no problem on storage server that I put my project.

**Comment by subjectdenied** [comment]
@helmiskandar : may i ask, how performance is with 19 tracking-images?
