### ISSUE TITLE
THREE.math is renamed to THREE.mathUtils and breaks location based logic

### ISSUE THREAD

**Issue by JvJefke** [jeromeetienne/AR.js#822]
**Describe the bug**
ar-threex-location-only.js throws an error when using `new THREEx.LocationBased(...)`.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'degToRad')
    at t._haversineDist (ar-threex-location-only.js:1:3186)
    at t._gpsReceived (ar-threex-location-only.js:1:2848)
    at ar-threex-location-only.js:1:1902
```

This happens because three.js has renamed the object `THREE.math` to `THREE.mathUtils`.
(changelog: https://github.com/mrdoob/three.js/releases/tag/r113)

I suggest updating the logic so it works with the latest three.js version. However this may break existing usages that make use of the older three.js version. I suggest putting a clear disclaimer or making the code backwards compatible.
(ar.js logic that uses `Math`: https://github.com/AR-js-org/AR.js/blame/8662537d2dc1701afc4eadfbf7b04db3341199de/three.js/src/location-based/js/location-based.js#L161)

**To Reproduce**
1. use three.js version `0.113.0` or higher
2. call `const arjs = new THREEx.LocationBased(scene, camera);`

**Expected behavior**
The code does not throw an error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android
 - Browser Chrome

**Comment by tranhogdiep** [comment]
I same issues, I downgrade to r0.146.0 for the same with the repo but still happens. @JvJefke do you know if the revision of ThreeJs will work?

**Comment by DougReeder** [comment]
Likewise, this breaks with version 1.4.x of A-Frame, which uses a recent version of three.js

**Comment by JvJefke** [comment]
@tranhogdiep 
I downgraded three.js to 0.112.0 and that seemed to "fix" it for now.

**Comment by DougReeder** [comment]
https://github.com/AR-js-org/AR.js/pull/523 would fix this.
